### ISSUE TITLE
Configure size compare to not use compression

### ISSUE THREAD

**Issue by kwonoj** [smooth-code/bundle-analyzer#27]
I have configured `size-limit` to not use compression, also would like to apply same for size compare but not able to find it. Is there way to configure it?

**Comment by gregberge** [comment]
compression: "none" https://docs.bundle-analyzer.com/docs/size-limit/#check-size

**Comment by kwonoj** [comment]
@gregberge as asked in q, that's what I configured:

```
//config

module.exports = {
  files: [
    {
      test: '*.js',
      maxSize: '5MB',
      compression: 'none',
    },
  ],
}
```

but in checker I got this:

![image](https://user-images.githubusercontent.com/1210596/75183879-4358e980-56f8-11ea-9042-77e05e27e6d9.png)

Size change's being reported as gzipped.

**Comment by kwonoj** [comment]
size `limit` is working expected as config : 
![image](https://user-images.githubusercontent.com/1210596/75183941-5cfa3100-56f8-11ea-981f-629527b4112c.png)

**Comment by gregberge** [comment]
@kwonoj yeah the presentation and the "limit" are not linked actually. Open to a PR to make it better.
