### ISSUE TITLE
The bundle analyzer app appears to be down

### ISSUE THREAD

**Issue by tim-soft** [smooth-code/bundle-analyzer#41]
Loading up https://app.bundle-analyzer.com/ gives a blank page

Taking a look at the network requests, there's a 503 "Service Unavailable" api call to `https://api.bundle-analyzer.com/graphql` for the query 

```graphql
query User {
    user {
        id
        login
        latestSynchronization {
            id
            jobStatus
            __typename
        }
        installations {
            id
            latestSynchronization {
                id
                jobStatus
                __typename
            }
            __typename
        }
        __typename
    }
}
```

Edit: if there is something I could contribute to get this working again, I'd be happy to help, although this seems like a devops issue with heroku

**Comment by chadhutchins182** [comment]
I think this project is done! #38 (Greg's reply)

I'm not sure what it would take to move to another hosting provider

**Comment by tim-soft** [comment]
someone with access to the heroku logs could give more insight into the issue, @gregberge could you take a look or give some guidance on rehosting the server elsewhere?

**Comment by chadhutchins182** [comment]
@tim-soft www.bundle-analyzer.com DNS A record is now missing: https://www.nslookup.io/dns-records/bundle-analyzer.com#cloudflare

**Comment by gregberge** [comment]
It is, I shut it down.
